extern "C"
#include "dianutils.h"
#include "httprequest.h"
#include "palservice.h"
#include <QDebug>
#include <pvs_hal.h>
#include <qnetworkaccessmanager.h>
#include <tinyxml2.h>
using namespace tinyxml2;

std::string GLOBAL_USER_ID="2018";
std::int8_t GLOBAL_CURRENT_STATUS;//全局掌脉状态
std::int8_t GLOBAL_CONTROL_CODE;//全局指令

const QString AddNewUser="1";
const QString UpdateUser="2";
const QString DeleteUser="3";

PalService::PalService(QObject *parent) : QObject(parent)
{

}

PalService::~PalService()
{

}

int PalService::getPalmStatus()
{

    return GLOBAL_CURRENT_STATUS;

}

int handleInit(PVS_APIIF_GUI_STATE GuiState,PVS_APIIF_GUI_MESSAGE Message,PVS_APIIF_GUI_BITMAP *pBitmapArea){
        pBitmapArea=pBitmapArea;

        if ((GuiState & PVS_APIIF_MESSAGE_PROVIDED) == PVS_APIIF_MESSAGE_PROVIDED)
        {
            switch (Message)
            {
            case PVS_APIIF_MESSAGE_PLACE_RIGHT:
                {
                    qDebug()<<("放上手掌\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_HOLD_UP_HAND:
                {
                    qDebug()<<("放上手掌\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_CORRECTLY:
                {
                    qDebug()<<("请正确放置手\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_CLOSE:
                {
                    qDebug()<<("请将手靠近\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_KEEP_AWAY:
                {
                    qDebug()<<("请抬高手掌\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_MOVE_AWAY:
                {
                    qDebug()<<("请移开手,稍后再放回\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_TEST_RIGHT:
            case PVS_APIIF_MESSAGE_SAVING:
            case PVS_APIIF_MESSAGE_AUTHENTICATING:
            case PVS_APIIF_MESSAGE_STOP_MOVING:
                {
                    qDebug()<<("请保持\n");
                    GLOBAL_CURRENT_STATUS=PVS_APIIF_MESSAGE_STOP_MOVING;
                    break;
                }
            case PVS_APIIF_MESSAGE_EVEN_UP:
            case PVS_APIIF_MESSAGE_SENSOR_ORIENT:
            case PVS_APIIF_MESSAGE_FLATTEN_OUT:
                {
                    qDebug()<<("手掌放平\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_FINGER_OPEN:
                {
                    qDebug()<<("请张开手指\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_MOVE_FORWARD:
                {
                    qDebug()<<("向前移动\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_MOVE_BACKWARD:
                {
                    qDebug()<<("向后移动\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_MOVE_LEFT:
                {
                    qDebug()<<("向左移动\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_MOVE_RIGHT:
                {
                    qDebug()<<("向右移动\n");
                    break;
                }

            case PVS_APIIF_MESSAGE_RETRY_RIGHT:
                {
                    qDebug()<<("重新开始采集\n");
                    break;
                }
            case PVS_APIIF_MESSAGE_FAILED_RIGHT:
            case PVS_APIIF_MESSAGE_BRIGHT_MOMENT:
            case PVS_APIIF_MESSAGE_BRIGHT_NG:
                {
                    qDebug()<<("重新采集,请不要移动您的手\n");
                    break;
                }

            default:
                {
                    qDebug()<<("采集中...\n");
                    break;
                }
            }
        }

        return PVS_APIIF_OK;
}

//register/update/delete from YUN

void registerPlam(QString vein,QString opType){
    qDebug()<<"ceshi post";
    QNetworkAccessManager *m_manager = new QNetworkAccessManager();
    HTTPRequest *request = new HTTPRequest(NULL,m_manager); //or null network acess manager instance, http request can create it's own access manager
    request->setHandlerFunc([=] (QNetworkReply *reply) {
        if (reply) {
            qDebug() << "22222222";
            QByteArray data = reply->readAll();
            Dianutils dianUtils;
            QString string_data = QString::fromUtf8(data.data());
            qDebug() << string_data;
        }
        request->deleteLater();
    });
    QString venn = "XhgAAAEEAAAAAAAAAAABAP//MgZDRDAyQhgAAAAEAAAAAAABAAABAAAAAAD+/0U9n+pPApipG7UddAq6PwC4Os77C5i04rZTSXoQQgFJkykOdmjVLHf2kyO+ztj8uELPclxKsdaFaEL5Kbws11iICTEA85obPm7R8Vvib1anjtULifevbKLftZO+NgAdSKYH0SQIffaznHnWkafBfzq0Jf9Iqgpk1Qr+kwsYg0LD/e4c6WC0T5G/Cqoh4doNmRGMmSnNtZ13NErK4g8UqsIJG865y4bap2BF7cnS3ZBO9tfyy8NdPzzDAclGfT9Mb31YYiY6Hu7KAeDFDTBsJRvvaO7NNpl+c5cF/EaYuN5ttPRp6skAx9W8dxjhJJ+20VEY5Gir1qzqGYddSzh7yrENhIObT2aLtZJKNIEbmoO731WQ8BSwazuVEei5rOjgOxWIXxtBPHkZ1RTm9VKR8fW2DJnEIWXv7X/p9AUu5nyvRMHCMYU1ACWI9oRpms3azIDkmO07SKK5FeGx/HzF1cURWJLDFTgsRGkATcZzWwwa7GR5M7hjDnAF51fKad8UIuf816OTep9ZpK3GWmVDWVN4/NmnokK3uU+jr1S+mKkFLGzltWVY9uXY87qsvHN8MeX/lNCM5TcEZReqitG9UVU01iG33aYmQFtuYxonoxiCupCK+Ib/+GY0m6MBJbxAnAiz4gJOI6vdCblCGv8jLF7Hwi7b2xwS7cF7Y9ZQbpe9t0tI87Cc8gWHwPvNBu/HS2LflWeeMsrhwTDmP6NpnkyqOrnkqojpb1KpzeG9b6trpMGhAdiJaB20PK1evERfi8/8Qqd+mkO1itqqMc2gbidN2sq/OFRFIWkfZrcrXt5bCKmCf1EguUmBi7fdGtmalvsF1imenJC2uHT2xAfYaxxwJw9dChVxcg4nvEAFAFRTFd4uJyzh/QkCuuPPB6LfNMy7/bygh0EFK0P8nJwPJvRqHcUCgnkuvljssXtVh8yV/0X0KAz0tHRT/G9Eo7XiuuE1Bw6pjMmNMsRFsGxLS0iJ7kjps9eV03yGTj6rja0YToVKgGm5PxGhe9ApunKCXC98OqRMlGSvA/JkOmPPEGw0iVRxhFAS45Pvc/XzuQJ5yRz7+I4BE56+Wj/VsgaQ+V+41IMdP9XRDlUF0CM+ccx8JRUIF8qC7J5V4/GEkDaPj+mVH5yur4QRKl/xxzlZTZR+UjGMu3ThhagpBN8nSilcwaW9N5+PI861BafC1OsmpQGtadUcYAtLvWEu3SFS0kX5Wb1McgDXRPdec8W8cv+fuNedeuNmPaTCD3S0CoRhmBa16/hhvQjcGkNF/XThTnOiYKq9dQdtv88bE2XpE8zyrtLtfAY5HxjhX9k9uQot42vpVtNzF4kNI75FmWtYsr+hYQMlDAVFh7UqGwCvc2AFaT0qEOxRKmkohNniMbI8Ak31ht6HtFFz8NmrMmQAryGi+i60L57Yf0H9KodxLnyC+SbbKxeLnYa19m9yB+GaYrc6bQD1VIURrC+Upuj7va2vdvsSobcO012B6L3zwY9/w1au7FiNmPnCZveosMIThjZ01BkYTIgkgN1mTFLr1KW9jDChZL+Gy6zw5o0mC5cq83Bns1Ptvez90II/FV5M7ubnFMesvifCbtUUhASxkRVTKQEGRyiiDrLKC8d8N2pMITQeCrOmAkG6sc0OGq2Fbr5/S/SvMvbGjyCEjTMEJhUaTb9YvDJ8KZ0SYMEjQUejaLqreqeTsnIuqnemILBSDhqZ78L4F5EqILxF0eP89dvGVpsA010m16XHXVnA0gyOIc/av838EjfHFBaJ6AN5s5TRECR/J4mylt+QeNpxREpdX/wdlfu1VuO0ge806yg29ItwxdpM8XSpHK8OaPW51Nj7nzHdMfUlAmErmE23dpZ76JqqwX0huAOyrMmWZMDkDYTg91URBbwQskc6XZzITehAcsvpvAhjzXEPIPxrTDtatoSqnyHvZX2Pai8DXFkN1hv7xefnEekorr9d7KMT1yTanHMit5lDIo0eSCR0U/iNQY0r6ScGddS7rlgO1okAdHFqf5lNkrZmTJWqHUVn0hMpNSBYRoOm+Fi1tsPXYo6tRGxGza+hOzOumfXFoR0iOYC+PZFW2SPmho1chHPRBvnc+nHxc5S/Zi8CvLI9dcnMi4ew19PHawBZbY806uxao1M4J4R8tXs+dLQJXupJCY0z+Y7U7I/yAvhACF8z+yfXgXgKIQTIDdGXZAQHBY+ze2YmlSlZB+KNobkg64NysWGTBDzpU23VPhYMYr5fMnHgb8bCeuuL5Smu1MFRxTBZmxYEzf2d9Coz5GtG9/q5c9yP+hFf4DnRkk94rib+nndHpkLalnl/eJIpZx3VttThgpOH3ziBGjo49MmD5RrGj+ec/WpmhilhM4GTT/1Gr/Z+mcRrQvzD/0HmT6UYHH4v4rAySrdHKJbGB0sFnCPPR0yurdTgBgl0NlTuoaCU0M9yUhCHJgVS7rXJWUe0awKTfVrErNKrohWjTGKs6p7Y3PZ516UAo4RZ/b1v7Q22K3c86RSGfBEuSW0xrJHjBg9JtZiGjTrZTKujBndRCQSpjUvyphoJUBwPo9FddRq7MY5K53ud8fVtroqL5MSMS0Nk65bcPKEwrg6zdkQwGlO5LsHbkSAnJBF7mSXP1DcHDPoYlaFUHMTUOicvIEcoL79BCLjLhbGKR9j5K1oOY9cDUo5AolYCSTIRPjdIy6/YeMjdLMgZe3np3F4XUYd0HU/1Ra9XJpd+260N6+LsQUhYueRJCaEQCRmj/st1YFj9kqPDsw0USRF1EfEI8FCtZCf2cjI0Vqu6Dz7D9WUptzF/ATaO00t0rqXPKeCyxTSXnQ6kpGV/EGS9k7BcKgjK1h3iB/tncadKevHsow+oKuKUBMU2pygAjSesuRfEEL9Mq9rcnt9MyIQ5bMY4gt034B5+mGt8qCkUJNS0RZXP2vH1mnewTimzICboL1EPiyUo1e46//bt5mPTHW2riKmWRn8aAZnbRC/GCpC50/RJ6cKO1fhlA1ftnJHi5OjlOLZ45c5WYl0ksbjW4qUfP7wLYwCUi7eKaKC+GEW7LxMm8EXfLs61Nn8qZ10DBdqGU1A4jmL/v2I4BzmEPK2GLwmBtoIcBBOhZ6scOwMhBcXo9phF7E+BYEd/eRV7nMZjL5vlvziSCz90REtbmfA2v7XuudAJrwLgrsISiWURVrnNGV0qTnVTsAhsjUg8y/dldj4VwtRJD0mdm6EpWWPa2xBM6aTFvsDyYf8I0Glw9juoxw57XD6qKubb0BV2QOjGBNG0LzoksMeW9RmpCBvrWBlzlggwDQdbktimGmZFhd1ko74mu4hdV0nUiAoEdw3bz0cQ1950VGKzz/2CNJFOFEZoOTbeECxdn9GEQx5ZAzlwD5X/VB9Y5Rs2DqJ5A/6PHI73+BZfjvoFdJiw9JHDxuBUuqam6hsv5tHFpMv5aieu/M+AlIgoHvAD2v5qbBzOKLGhRb9BCj2ULeump7Cyha9LZW3MAqFVvdK5lKnNEQcJY8hLn4LXn3e2+HP7zJSDEmSLPg7LLq4A8r+0p0ZI8FpNzlkbXr6fK+rsBxD2Eb0fr6HaJMFPkjG6f4BCPYaM1OzhhgJ1pvYcqZBS6bLZJ0njMWEjZSyVLCn6fKkb4/ZC76HedCkAS7UeEzUnJjsPPlggdsyKqHAyQyx+Oy84WO/VFTcAlpSsxbOE6cBr5Ozlln4fViFGCxoeMB6AhGQUv9ZVOY3oHtb2r5i78W5KV4fd2WgDOM6Uuy/oVSX64ZQVkjKkr0+Vc23eCw+j6J5CW/rc1jN6dm+DNv8b59VDX+yMmAoLqR3+RkZe6zsNujyYX8SLZ4fxRib6fIvypEg0LkOaCzt0QfI/q3Ogna50tCidih9VzVh99vx7VjVD1xiiUxJjFlCG4tVBRpi0PP4PwaZ8LJqts+OVKfMObT/ChFwfj818ibMNjmC0TSACvKI/xiTzgVj4ZhQq/Kcx3kW/9zRFfcV+aaeYlpCf3nmiT6LByV98W2iULOXpX/Hqi307DPYDC8GyOGE/KlJKCSQmnLTWZRtweCb0fxfNcbKAcNOg39pFYxA4oj6ps7f8s3x9Zj6C63Fv3RgmXnWE5DFTTm3ofZTGoBNYLWrud9fnXD4gVv/o84Oh071suFVuk4EaRrtbGWkDATLH+yAElmp7c68GaM0MLGMIIiWXeOYcqLglRJ0leiREw35oTIE4iv0kQdZujTnieyDXP+9QiHXyODrdh1nIPTlGOTtCiAe4lMrHsWOv8Tpo42DPLFnaGbbZd8u+3KfDX3Q/3GTB9apZFSKSl9hTxntvgiWG8oL1LO1i/ZF4wztuQYeA7Z0KtF4bSyeTWScdrvZL4+lfO0xzna8LTWn1KXTt0O6CeTLhqw2SZZW3MwI0C7TGUeoL33o2NBd72oRmbYaZvCWWG5XrV2t7hkKlN96nJHqAx5CeO1WoYZQ1GPIHDJsljMEgKB4c/xPUpFShFBYTgp9Z41bY/bJXL4C2YjdE9sEWwY/ZjuZVFrLzQpCc1j9QRWbAuhATzZCPI6/cRkcBYivv42IZmBsHxApmA5sm19Yw++Nwdt9nzfQs6aCCdOHgeSRzXTGaPc8ALBJXrEDeuuCLDTVpnBoB75ftMDR5vhL/GN2WZsWOmbASu5YkrHtHuqY8InHDr7lpSD3vI8ADDJBR7LvzuiQuokW9fx3xkcOZ4/b/wj9kq3CLCe9Ts9rx922v/wZCTq3djRl73/bqxGdSEGS8qG1Pizp15fEuvLP0EiTg9dbNUqgwvvR6bbSzF1vBugrcByA9bBa54iEWMffViud97kvkpkAHBK5Or9tff5RpqkLcZsQeSwZ4FkuWw54WPQNt3tOm2maiR9BqL/tUzstZw5yrjPK4xp+F9GWAM0xYrtqZ+wHHOJXFl0vKId5r70D0wNaxQ5RF9s3oqfobL8tgacCTzyG8WD9wOGunbjisvOyYhNwR257P0HLg2gm02i6tNtrlTmUsn0KpDAJOqW5Y0g4qB5NMqOYYQ+cIBBpYBC+lCe3n4Roge8gfDmZngf4crSjF7QWiuF9JuSwFuhz92eouIAgCjw5DfVANb15sahilkuUZRDq/yOPwHEV1ZDfdpWWyvlqhQ8dQU2to1ZY0q0d7bRLGL+Fc8DcF+7zWFbeztlUgRf+NfQb5eQRcNA0pAf+fazr/etZ0ezEW+sQcj/UWcdSYc22C6tC2/U59k2rvzQ5BRGiTDCtyajQtcMmoqnEbpjewSCZjaKSqvNl968iRp8ioBpoe1SEwQ4cwtLl5ess1RD34sja9oO8OdeU29kZ7VhUSU6MRieqtW6t8aCd5PCSa1gjHlKXJoTuusTS5mIBx8n9wWZgEfX3UB6eaQ67r98TK1IFWRj6vR1lijTk+CPB763JjMyWnlhUipBczMO4wkqVKj1jNBorRHQSNqs19dlWO5LxDVBoPbAgUpChoq0G5J+xzEwembrSxsvNDXqbXIsLscvAcpaNwZrijCD+g1uvoHIDAjGhecIS7PvDvp4BEoQl5FroBNeuHB6W/8uvgvJNxRxotK68UsfItblhTMhcAiJlxkrtZ3HfwtdqLr3ol5xZYTr7roo7+lx0oLmbeJ2dMpPqJaibS4c3DSqMP0uTG7Q3/lL1l+BRUIEMrj5VCYHtES/6Vw2zeQjYy8G53NvxLi7xMFKhbJHOmt4Vzk+DwJLX3zsDtMi9kkDt6EaprGDKT6S1k1RYiMKj29IInRBrZBVmeusD60K5D+KDF+t2K6u0oDJE7f736/gKTeS6eOeS+E93ydQOhCVMho4HjK0TFLecLndzSrgCLm5ZL06iT8vlH5F58fxu5mgCWIbVX92Vgjp/nlrt334UWgKLUpR/NhcgE0xLD8T9hY0eiFfT6D/Kun3lal+Oi3cmOk7HVgETGKRf1I1vWtwMFWPqzfgyGNONmAai8cMRVbKNN5SBt0LITi3xh3UE26ojH5XcylVJFYY16kGrVJb6ahm1pa18iSNxkySWJSyQ6kWQXxSdfZnCoUf8Dlld8YGJsbwOaiKiz0PuIZyPhFEFcE0Bi3zknw9srtffI+T+gbf7pIhV1DUMDd6ijMS047w8adKLMHty5AmTZTM1sHPv04gzDjUTqiBssaO31m0QuVlH5KnQ1Ga6Xmt0WtzpKD8bCimnCC+vs22pamudXsvptQI8Dk3HAAenOQ54z95fQaw3JhT1BJWk19G21eB8mPyh+wAZFMwSAjtAB2UVke9neAYjIfNY6Wro0QtJ/QwPKDG/Ufsmla9N+a28NX0pnwlnAq3fbZiA15CV9XMb7ylUtm90s8zlliVMAo7b9F6XBR7FTZOVKeK8DyYf5HEmNUn6aBbrIeJI8+DMaeVFAIa5FafRXNMnfJVNAyYeYcSHOEI5EZoqjsdbc4/Um5WaTLLAWYaqySI6wwstSJyss0KTxarBjHL+GOQtckhHBc3SuMhO9kw9dIPJGi469xDUZv32Q0tCzEoyewCKOYKvyRj0xV2EnA6Pm9ADFYTKpfNvIDsrvsdjl6MCw14zHuuFi0RKnvTC/T3GSbYJ6tbALpmw0UnU7dvKRtr8gsTU8toKyOkc66JW/5ZdFAiMhIhrTzFBBMvsDAo9BJiLwfLTHhWp+auoLb6f/GIqQdRznqEva0/0DCzMvJKvVF9Am/2u27ksVePuG/jc7aPpsCgFnVUsCMUpHcTl5s4auDEfEI/+T9+gkw38r9fFb8nuJjfsRApO5Sh0/TS0P0mMzw2ZRDE8uHZZGwRibVT1QfTDwYnvYdxGXIG8UNC/B6EoznL71c/GhQthWZ/+E/mOOeIaEUxFf9CfaBBP8maSauV2NVKrQULnofuAOmuO6/yrMmiumxZ3dZqc8pUue2o2s9zZBelRwpjWTDVscCWlb62jPoOold6J/CudF8/3O3iGLOjkG5kcxHthm4zvXrEb6VY0bkbuXGDEQuSStIJJ8Y3/PhB34PckDLo+FNmMQVnlt27nddKCan4jDJGyJTU4jxSAseSa8bZtuwNNIN+0sEaE9oNxl6nII6tYJTR/kaWdV7RnN7OtZrRMPn3uR/p8GGfxxAPJR8Ihy0bZdDqlHafokL0UUYMGr9CgPZn33S34eMwneMaEn/sjFAc/2ZTCVeyVaD20nKqTKB8oVjA+YdnEsD0jIXzElZgMLOM2CvnnZnzcQ0P2E6tygwWpxWgMqTla+tgT0Y+IRTzF6SDsunwnuj9EWGek62kLDdz0o+wY72hkk88MBC/YKeIq1K6/QIR0Box4kEFEnAKUsRjtUzw04V4KMCR/AB9w2BxwoCzm7DH4ygWz9lhotVAJI8EbEvfl/Ylp2Szk+3nZuvzazTUvxp0WZbDEeWRaEomS1oTXqNTHlq2lezi3QfGNEsoS+AZ1oDNkooAZjxV6t5ckdh2PdtOn+Q9dzYgVH4h/O1jdPlHdTy3yzri8XawWERQp7U8Jdhx6X96tBR+kdYKNS/QC41X7yVAOM5p6UX21HkvB3EjrMPTd1iGzyxaQZ4pgD3zlWGEGI8Ny21uysLqdv6zyQHzg4oOPfeTapbn7HuXjLW0OWeF9AcHKxI2qF7+FX/PBMHETKXeJ3HIocsREJ90n4rz2dfknuKM8QPXSoPlrDIOUPPQBhcg5ZccGxbUN/ujT1Yp8kbimJrQcAKsHOyluYk/+ac76FNFR3PUTHewySiTzbSnu7yDvuSnyAQYr33NOBSQc/57yS8axik1jUsRfT+HGRi4GExQhyC4XHwJXP5bU6qnp+fBcEYXS9xfb6c3Vl7c/0OlZqT3V1icsiZcUS5gvqH2+h7CvXRCz1CUEEAwBz8/7Eu6tlMgFNapp8w4ZiY+OUUgNvN9bYogK4evk/3qGZ0MhLr38L8t4821zIiCjnfDWlHEREW6RCSbJGbFidcRdQH3iZZN1gsJA+y6C5MQLBOAdsHSadyQFHH1IthqurJq0uvY6SigEYWlcDTMiYS0OsT66Gw/a59ExUGzSLcz4a1Io2NepwIxgz140V5gZue6IfXfKC7xAIkfnZ0m86Zb+zTNNCNQdJo9HY34M+supv2vvv/EI6AmnBrFgb7SMmCEVtDpxMbAtSdzyqjw/mDSYvBgGvL2B0lrPI1xpUrXdkLiuk/dIskZ6F1Cpk9xmbj+5AmhGPEGTMZ2lynUDv69PCigN2w7vo0O2p6yrfVmjcTMIwhrwynT8iXcPomD/yDDnhTCi6xPJbIZMEfMqZufWrfooZ/J41BATK4qWDwK2Y1iaZEcGSRm/xy9XSE8PWiZCXnWW3VtcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    QString url = "http://118.31.35.229:8080/palmgw/app211b81d83c2048b792c030b928e7aeae/C1001.htm";





//    QMap<QString,QString> params;
//    params.insert("userId",QString::fromStdString(GLOBAL_USER_ID));
//    params.insert("vein",venn);
//    params.insert("type",opType);

//    request->post(url,doc);
}



void PalService::init()

{
   qDebug()<<"初始化以及获取状态，时时提醒用户手到操作"<<QString::fromStdString(GLOBAL_USER_ID);
   PVS_BIOAPI_RETURN pbr;
   hal_pvs_init((CALLBACK_FUNC *)handleInit,&pbr);
   std::string palmData="0";

   registerPlam(QString::fromStdString(palmData),AddNewUser);
   hal_pvs_enroll(palmData,&pbr);
   //lock done get data finished
   registerPlam(QString::fromStdString(palmData),AddNewUser);
   qDebug()<<QString::fromStdString(palmData);
}



void PalService::ecoll()
{
   qDebug()<<"注册扫描";
}

void PalService::capture()
{
  qDebug()<<"获取数据";
}
void PalService::cancle(){

   qDebug()<<"取消刷手";
}
void PalService::terminate(){

    qDebug()<<"关闭设备";
}

//控制指令exec
void PalService::changeValueByCode()
{
    switch (GLOBAL_CONTROL_CODE) {
    case 1:
        qDebug()<<"开启初始化";
        PalService:: init();
        break;
    case 2:
        qDebug()<<"开启注册";
        break;
    case 3:
        qDebug()<<"开启采集";
        break;
    case 4:
        qDebug()<<"开始关闭";
        break;
    case 5:
        qDebug()<<"取消采集";
        break;
    default:
        break;
    }
}

void PalService::setChangeValue(QString value)
{
    GLOBAL_CONTROL_CODE=value.toInt();
    qDebug()<<"set control value successful";
}
